import {
  Activity,
  Ambulance,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  Baby,
  BadgeCheck,
  Banknote,
  BedDouble,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Car,
  CarFront,
  Check,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudLightning,
  Coins,
  Compass,
  Factory,
  FileCheck,
  FileSearch,
  FileText,
  Flame,
  Footprints,
  Fuel,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Hospital,
  House,
  HousePlus,
  IdCard,
  Info,
  KeyRound,
  Landmark,
  LandPlot,
  Laptop,
  Layers,
  LifeBuoy,
  LineChart,
  ListChecks,
  Lock,
  Luggage,
  Mail,
  Map,
  MapPin,
  MessageSquareText,
  Milestone,
  Minus,
  Package,
  Paintbrush,
  PenLine,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plus,
  Receipt,
  Repeat,
  Route,
  Scale,
  School,
  ScrollText,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShieldPlus,
  Signpost,
  Smartphone,
  Sofa,
  Sprout,
  Stethoscope,
  Store,
  Sunset,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  TriangleAlert,
  Truck,
  Umbrella,
  UserCheck,
  UserRound,
  Users,
  Wallet,
  Warehouse,
  Waves,
  Wrench,
  type LucideProps,
} from "lucide-react";

/**
 * One consistent line-icon set (Lucide, 1.75 stroke). Content files reference
 * icons by name so data stays serialisable and free of UI imports.
 */
const icons = {
  activity: Activity,
  ambulance: Ambulance,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  award: Award,
  baby: Baby,
  badge: BadgeCheck,
  banknote: Banknote,
  bed: BedDouble,
  bike: Bike,
  book: BookOpen,
  briefcase: Briefcase,
  building: Building2,
  bus: Bus,
  calculator: Calculator,
  calendar: CalendarClock,
  calendarCheck: CalendarCheck,
  calendarPlain: Calendar,
  camera: Camera,
  car: Car,
  carFront: CarFront,
  chart: LineChart,
  check: Check,
  checkCircle: CircleCheck,
  clipboard: ClipboardList,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  factory: Factory,
  file: FileText,
  fileCheck: FileCheck,
  fileSearch: FileSearch,
  fire: Flame,
  footprints: Footprints,
  fuel: Fuel,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  graduation: GraduationCap,
  hammer: Hammer,
  handCoins: HandCoins,
  handHeart: HandHeart,
  handshake: Handshake,
  heartHandshake: HeartHandshake,
  health: HeartPulse,
  help: CircleHelp,
  home: House,
  homePlus: HousePlus,
  hospital: Hospital,
  idCard: IdCard,
  info: Info,
  key: KeyRound,
  landmark: Landmark,
  landPlot: LandPlot,
  laptop: Laptop,
  layers: Layers,
  lifebuoy: LifeBuoy,
  listChecks: ListChecks,
  lock: Lock,
  luggage: Luggage,
  mail: Mail,
  map: Map,
  message: MessageSquareText,
  milestone: Milestone,
  minus: Minus,
  package: Package,
  paintbrush: Paintbrush,
  pen: PenLine,
  phone: Phone,
  piggy: PiggyBank,
  pill: Pill,
  pin: MapPin,
  plane: Plane,
  planeLanding: PlaneLanding,
  planeTakeoff: PlaneTakeoff,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  route: Route,
  scale: Scale,
  school: School,
  scroll: ScrollText,
  search: Search,
  shield: ShieldCheck,
  shieldAlert: ShieldAlert,
  shieldPlus: ShieldPlus,
  signpost: Signpost,
  smartphone: Smartphone,
  sofa: Sofa,
  sprout: Sprout,
  stethoscope: Stethoscope,
  store: Store,
  storm: CloudLightning,
  sunset: Sunset,
  target: Target,
  ticket: Ticket,
  timer: Timer,
  trendingUp: TrendingUp,
  truck: Truck,
  umbrella: Umbrella,
  user: UserRound,
  userCheck: UserCheck,
  users: Users,
  wallet: Wallet,
  warehouse: Warehouse,
  warning: TriangleAlert,
  waves: Waves,
  wrench: Wrench,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, strokeWidth = 1.75, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={strokeWidth} {...props} />;
}
